const fs = require('fs')
const path = require('path')
const file = path.join(__dirname, '..', 'electron', 'main.cjs')
const c = fs.readFileSync(file, 'utf-8')
const lines = c.split('\n')
const before = lines.slice(0, 178).join('\n')
const after  = lines.slice(248).join('\n')

const newBlock = [
  '',
  '// --- REAL PTY (VS Code binaries) ---',
  'let pty = null',
  "try { pty = require('node-pty-prebuilt-multiarch') } catch(e) { console.warn('pty:', e.message) }",
  'const ptys = {}',
  '',
  "ipcMain.handle('pty-create', (event, { cwd, cols, rows }) => {",
  '  cols = cols || 120; rows = rows || 35',
  '  const resolved = path.isAbsolute(cwd) ? cwd : path.join(WORKSPACE, cwd)',
  '  const ensured  = fs.existsSync(resolved) ? resolved : PROJECTS_DIR',
  "  const id       = 'pty-' + Date.now()",
  '  const send = (data) => { if (!event.sender.isDestroyed()) event.sender.send(\'pty-data\', {id, data}) }',
  '',
  '  if (pty) {',
  '    let proc',
  '    try {',
  "      proc = pty.spawn('cmd.exe', [], {",
  "        name: 'xterm-256color', cols, rows, cwd: ensured,",
  "        env: { ...process.env, TERM: 'xterm-256color', COLORTERM: 'truecolor', OPENJIRA_PATH: ensured }",
  '      })',
  '    } catch(e) { return { ok: false, reason: e.message } }',
  '    ptys[id] = proc',
  '    proc.onData(data => send(data))',
  '    proc.onExit(({ exitCode }) => {',
  '      if (!event.sender.isDestroyed()) event.sender.send(\'pty-exit\', { id, exitCode })',
  '      delete ptys[id]',
  '    })',
  '    setTimeout(() => {',
  "      try { proc.write('cls\\r\\n') } catch {}",
  '    }, 400)',
  '    return { ok: true, id, mode: \'pty\' }',
  '  } else {',
  '    const encoded = Buffer.from(',
  '      \'[Console]::OutputEncoding=[System.Text.Encoding]::UTF8;\' +',
  '      \'Set-Location $env:OPENJIRA_PATH;\' +',
  '      \'Write-Host "";\' +',
  '      \'Write-Host "  Taskify Terminal" -ForegroundColor Cyan;\' +',
  '      \'Write-Host ("  Carpeta: "+$env:OPENJIRA_PATH) -ForegroundColor Yellow;\' +',
  '      \'Write-Host "  Usa: claude / opencode / cursor ." -ForegroundColor Green;\' +',
  '      \'Write-Host "";\',',
  "      'utf16le').toString('base64')",
  "    const ps = spawn('powershell.exe', ['-NoLogo', '-NoExit', '-EncodedCommand', encoded], {",
  '      cwd: ensured, stdio: [\'pipe\', \'pipe\', \'pipe\'],',
  '      env: { ...process.env, OPENJIRA_PATH: ensured }',
  '    })',
  "    ptys[id] = { fb: true, proc: ps }",
  "    ps.stdout.on('data', d => send(d.toString('utf8')))",
  "    ps.stderr.on('data', d => send(d.toString('utf8')))",
  "    ps.on('exit', code => { if (!event.sender.isDestroyed()) event.sender.send('pty-exit', {id, exitCode: code}); delete ptys[id] })",
  "    return { ok: true, id, mode: 'pipe' }",
  '  }',
  '})',
  '',
  "ipcMain.on('pty-input', (_, { id, data }) => {",
  '  const p = ptys[id]',
  '  if (!p) return',
  "  if (p.fb) { if (p.proc.stdin.writable) p.proc.stdin.write(data, 'utf8') }",
  '  else try { p.write(data) } catch {}',
  '})',
  '',
  "ipcMain.handle('pty-resize', (_, { id, cols, rows }) => {",
  '  const p = ptys[id]',
  '  if (p && !p.fb) try { p.resize(cols, rows) } catch {}',
  '})',
  '',
  "ipcMain.handle('pty-destroy', (_, id) => {",
  '  const p = ptys[id]',
  '  if (p) { try { if (p.fb) { p.proc.stdin.end(); p.proc.kill() } else p.kill() } catch {} }',
  '  delete ptys[id]',
  '})',
  '',
].join('\n')

const result = before + '\n' + newBlock + '\n' + after
fs.writeFileSync(file, result, 'utf-8')
console.log('Written OK, lines:', result.split('\n').length)
